version: '3.7'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_DB: db
      POSTGRES_USER: doc
      POSTGRES_PASSWORD: 1234